[package]
name = "day6"
version = "0.1.0"
edition = "2021"

[dependencies]
regex.workspace = true   # Use the shared `regex` dependency
utils.workspace = true   # Use the shared `utils` dependency

[[bin]]
name = "day6"
path = "src/day6.rs"
