[package]
name = "day5"
version = "0.1.0"
edition = "2021"

[dependencies]
regex.workspace = true   # Use the shared `regex` dependency
utils.workspace = true   # Use the shared `utils` dependency

[[bin]]
name = "day5"
path = "src/day5.rs"
